### ISSUE TITLE
Plugin Configuration Fails

### ISSUE THREAD

**Issue by buffaloseven** [xchewtoyx/calibre-comicvine#1]
The plugin returns this error when trying to configure on Mac OS X 10.8.4, calibre 0.9.34 & v0.9.1 of the plugin:

```
calibre, version 0.9.34
ERROR: Unhandled exception: <b>AttributeError</b>:'ConfigWidget' object has no attribute 'label'

Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 285, in double_clicked
  File "site-packages/calibre/gui2/preferences/plugins.py", line 364, in modify_plugin
  File "site-packages/calibre/customize/__init__.py", line 150, in do_user_config
  File "calibre_plugins.comicvine.source", line 42, in config_widget
  File "calibre_plugins.comicvine.config", line 31, in __init__
AttributeError: 'ConfigWidget' object has no attribute 'label'
```

**Comment by xchewtoyx** [comment]
Thanks for the note.  I should have done more testing of the config widget.  Should be fixed in 0.9.3
