### ISSUE TITLE
SyntaxError:Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by SoccerNerd** [xchewtoyx/calibre-comicvine#10]
Trying to import into Calibre 5.26 and received the following error for the zip file I created based on the manifest file.

calibre 5.26  embedded-python: True is64bit: True
Linux-4.4.180+-x86_64-with-glibc2.2.5 Linux ('64bit', '')
('Linux', '4.4.180+', '#41890 SMP Thu Jul 15 03:37:40 CST 2021')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 43, 0) && Package KFX (from KFX Input) (1, 43, 0) && Action Chains (1, 13, 0) && Embed Comic Metadata (1, 6, 1) && Find Duplicates (1, 8, 10) && Goodreads (1, 5, 1) && KFX metadata reader (from KFX Input) (1, 43, 0) && KFX Input (1, 43, 0) && Reading List (1, 7, 6)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 477, in add_plugin
  File "calibre/customize/ui.py", line 65, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.comicvine.__init__", line 4, in <module>
    from calibre_plugins.comicvine.source import Comicvine
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 185, in exec_module
  File "calibre/customize/zipplugin.py", line 181, in get_code
  File "calibre_plugins.comicvine.source", line 67
    print result_text
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(result_text)?

**Comment by unclehook** [comment]
UP.

**Comment by jbbandos** [comment]
@SoccerNerd @unclehook I'm maintaining a fork, and informed @xchewtoyx of it (https://github.com/jbbandos/calibre-comicvine ), can you check if you still have these issues in my fork?

**Comment by SoccerNerd** [comment]
I've actually stopped using Calibre to manage my comic collection. Went
back to using ComicRack. While it's no longer being supported it's still a
better fit for my needs than Calibre. Perhaps I'll try Calibre again with
the new version 6.  If I do I'll certainly give your plugin a try.
