### ISSUE TITLE
Plugin is failing to download covers

### ISSUE THREAD

**Issue by MikeyTsi** [xchewtoyx/calibre-comicvine#2]
Looks like cover download is now failing consistently:

*****************************\* Comicvine Covers ******************************
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 5.2; rv:2.0.1) Gecko/20100101 Firefox/4.0.1')]
Failed to download valid cover
Took 0.00299978256226 seconds
Downloading cover from: /uploads/scale_large/6/67663/2952195-01.jpg
Failed to download cover from: /uploads/scale_large/6/67663/2952195-01.jpg
Traceback (most recent call last):
File "calibre_plugins.comicvine.source", line 172, in download_cover
File "site-packages\mechanize-0.2.5-py2.7.egg\mechanize_mechanize.py", line 199, in open_novisit
File "site-packages\mechanize-0.2.5-py2.7.egg\mechanize_mechanize.py", line 216, in _mech_open
BrowserStateError: can't fetch relative reference: not viewing any document

---

**Comment by MikeyTsi** [comment]
This particular one got fixed.
