### ISSUE TITLE
ImportError: cannot import name Comicvine

### ISSUE THREAD

**Issue by quantissimo** [xchewtoyx/calibre-comicvine#8]
I changed "PyQt4.Qt import QWidget, QGridLayout, QLabel, QLineEdit" to "PyQt5.Qt import QWidget, QGridLayout, QLabel, QLineEdit" in config.py and re-bundled the plugin zip file.

But now I receive:

calibre, version 2.68.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name Comicvine

calibre 2.68 [64bit]  embedded-python: True is64bit: True
Windows-8-6.2.9200 Windows ('64bit', 'WindowsPE')
('Windows', '8', '6.2.9200')
Python 2.7.9
Windows: ('8', '6.2.9200', '', 'Multiprocessor Free')
Successfully initialized third party plugins: DeDRM (6, 5, 1)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 315, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 417, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 55, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 195, in load
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.comicvine.**init**", line 4, in <module>
ImportError: cannot import name Comicvine

**Comment by kermititan** [comment]
I've solved it just restarting calibre.
Look at post #44 [http://www.mobileread.mobi/forums/showthread.php?t=213049&page=5](http://www.mobileread.mobi/forums/showthread.php?t=213049&page=5)
It seems it gets stuck with a previous cached file.
